In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os
from PIL import Image
import numpy as np
import warnings
import tensorflow as tf
warnings.filterwarnings('ignore')
%matplotlib inline

In [13]:
(X_train,Y_train),(X_test,Y_test)=tf.keras.datasets.mnist.load_data()

In [14]:
X_train.shape

(60000, 28, 28)

In [15]:
X_train=X_train.reshape((X_train.shape[0],X_train.shape[1],X_train.shape[2],1))
X_train.shape

(60000, 28, 28, 1)

In [16]:
Y_train.shape

(60000,)

In [17]:
Y_train=Y_train.reshape(-1,1)
Y_train.shape

(60000, 1)

In [18]:
X_test.shape

(10000, 28, 28)

In [19]:
X_test=X_test.reshape((X_test.shape[0],X_test.shape[1],X_test.shape[2],1))
X_test.shape

(10000, 28, 28, 1)

In [20]:
Y_test.shape

(10000,)

In [21]:
Y_test=Y_test.reshape(-1,1)
Y_test.shape

(10000, 1)

In [42]:
X_train=X_train/255.0
X_test=X_test/255.0

In [43]:
model_1=tf.keras.Sequential([
    tf.keras.layers.Conv2D(filters=40,strides=(1,1),kernel_size=(4,4),activation='relu',input_shape=(28,28,1),padding='same'),
    tf.keras.layers.MaxPool2D(pool_size=(3,3),strides=(1,1)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(units=50,activation='relu'),
    tf.keras.layers.Dense(units=10,activation='softmax')
])

model_1.compile(
    loss=tf.keras.losses.sparse_categorical_crossentropy,
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
    metrics=['accuracy']
)

model_1.fit(X_train,Y_train,epochs=15)

Epoch 1/15
1875/1875 [==============================] - 83s 44ms/step - loss: 0.2723 - accuracy: 0.9183
Epoch 2/15
1875/1875 [==============================] - 83s 44ms/step - loss: 0.1608 - accuracy: 0.9517
Epoch 3/15
1875/1875 [==============================] - 78s 41ms/step - loss: 0.1410 - accuracy: 0.9573
Epoch 4/15
1875/1875 [==============================] - 78s 42ms/step - loss: 0.1266 - accuracy: 0.9620
Epoch 5/15
1875/1875 [==============================] - 83s 45ms/step - loss: 0.1236 - accuracy: 0.9617
Epoch 6/15
1875/1875 [==============================] - 85s 45ms/step - loss: 0.1136 - accuracy: 0.9658
Epoch 7/15
1875/1875 [==============================] - 83s 44ms/step - loss: 0.1099 - accuracy: 0.9670
Epoch 8/15
1875/1875 [==============================] - 83s 44ms/step - loss: 0.1049 - accuracy: 0.9677
Epoch 9/15
1875/1875 [==============================] - 82s 44ms/step - loss: 0.1033 - accuracy: 0.9689
Epoch 10/15
1875/1875 [==============================] - 83s 44m

In [73]:
prediction=model_1.predict(X_test)

313/313 [==============================] - 3s 8ms/step


In [76]:
result=[]
for i in range(prediction.shape[0]):
    result.append(np.argmax(prediction[i,:]))
result=np.array(result)
result=result.reshape(-1,1)

In [77]:
result[0:10,:]

array([[7],
       [2],
       [1],
       [0],
       [4],
       [1],
       [4],
       [9],
       [5],
       [9]], dtype=int64)

In [78]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(Y_test,result))
print(classification_report(Y_test,result))

[[ 963    1    1    2    0    3    5    0    2    3]
 [   0 1113    6    6    0    1    2    0    7    0]
 [   3    0  997   14    0    0    0    8    9    1]
 [   0    0    2  990    0    8    0    6    3    1]
 [   1    5    4    1  930    1    6    6    4   24]
 [   2    2    0   23    1  854    2    1    3    4]
 [   6    2    1    1    1    3  940    0    3    1]
 [   1    3   13   13    2    1    0  978    3   14]
 [   9    0    1   13    4    6    4    4  920   13]
 [   3    5    0   10    6    9    0   16    2  958]]
              precision    recall  f1-score   support

           0       0.97      0.98      0.98       980
           1       0.98      0.98      0.98      1135
           2       0.97      0.97      0.97      1032
           3       0.92      0.98      0.95      1010
           4       0.99      0.95      0.97       982
           5       0.96      0.96      0.96       892
           6       0.98      0.98      0.98       958
           7       0.96      0.95   